# [brewery]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [brewery]    Script Date: 27.11.2022 23:42:08 ******/
CREATE DATABASE [brewery]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'brewery', FILENAME = N'D:\Programs\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\brewery.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'brewery_log', FILENAME = N'D:\Programs\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\brewery_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [brewery] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [brewery].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [brewery] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [brewery] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [brewery] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [brewery] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [brewery] SET ARITHABORT OFF 
GO
ALTER DATABASE [brewery] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [brewery] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [brewery] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [brewery] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [brewery] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [brewery] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [brewery] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [brewery] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [brewery] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [brewery] SET  ENABLE_BROKER 
GO
ALTER DATABASE [brewery] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [brewery] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [brewery] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [brewery] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [brewery] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [brewery] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [brewery] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [brewery] SET RECOVERY FULL 
GO
ALTER DATABASE [brewery] SET  MULTI_USER 
GO
ALTER DATABASE [brewery] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [brewery] SET DB_CHAINING OFF 
GO
ALTER DATABASE [brewery] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [brewery] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [brewery] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [brewery] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'brewery', N'ON'
GO
ALTER DATABASE [brewery] SET QUERY_STORE = OFF
GO

# [dbo].[isValidEmail]

In [0]:
USE [brewery]
GO

In [0]:
/****** Object:  UserDefinedFunction [dbo].[isValidEmail]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--TABLES
CREATE FUNCTION [dbo].[isValidEmail](@EMAIL varchar(30))
RETURNS bit as
BEGIN     
    DECLARE @bitRetVal as Bit
    IF (@EMAIL = '' OR @EMAIL NOT LIKE '_%@__%.__%')
        SET @bitRetVal = 0  -- Invalid
    ELSE 
        SET @bitRetVal = 1   -- Valid
    RETURN @bitRetVal
END
GO

# [dbo].[isValidPhoneNumber]

In [0]:
/****** Object:  UserDefinedFunction [dbo].[isValidPhoneNumber]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[isValidPhoneNumber](@PHONE_NUMBER varchar(30))
RETURNS bit as
BEGIN     
    DECLARE @bitRetVal as Bit
    IF (LEN(@PHONE_NUMBER) != 11 or iSNUMERIC(@PHONE_NUMBER) = 0)
        SET @bitRetVal = 0  -- Invalid
    ELSE 
        SET @bitRetVal = 1   -- Valid
    RETURN @bitRetVal
END
GO

# [dbo].[products]

In [0]:
/****** Object:  Table [dbo].[products]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[products](
	[product_id] [int] IDENTITY(1,1) NOT NULL,
	[product_name] [varchar](30) NOT NULL,
	[product_type] [varchar](30) NOT NULL,
	[upc_code] [varchar](12) NOT NULL,
	[prime_price] [decimal](8, 2) NOT NULL,
	[retail_price]  AS ([prime_price]*(1.38)),
	[discount_price] [decimal](8, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[product_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[product_name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[upc_code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[stock]

In [0]:
/****** Object:  Table [dbo].[stock]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[stock](
	[product_id] [int] NOT NULL,
	[amount] [int] NOT NULL
) ON [PRIMARY]
GO

# [dbo].[ProductsStockView]

In [0]:
/****** Object:  View [dbo].[ProductsStockView]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


--VIEWS
create view [dbo].[ProductsStockView] as
	select product_name,
		   product_type,
           upc_code,
		   prime_price,
		   retail_price,
		   discount_price, 
		   amount 
		   from products
				join stock on products.product_id=stock.product_id
GO

# [dbo].[customers]

In [0]:
/****** Object:  Table [dbo].[customers]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[customers](
	[user_id] [int] NOT NULL,
	[customer_id] [int] IDENTITY(1,1) NOT NULL,
	[email] [varchar](30) NOT NULL,
	[customer_name] [varchar](30) NOT NULL,
	[phone_number] [varchar](30) NOT NULL,
	[address] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[customer_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[phone_number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[orders]

In [0]:
/****** Object:  Table [dbo].[orders]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[orders](
	[order_id] [int] IDENTITY(1,1) NOT NULL,
	[customer_id] [int] NOT NULL,
	[order_date] [datetime] NOT NULL,
	[order_status] [varchar](30) NULL,
	[total_prime_cost] [decimal](8, 2) NULL,
	[total_cost] [decimal](8, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[order_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[order_details]

In [0]:
/****** Object:  Table [dbo].[order_details]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[order_details](
	[order_id] [int] NOT NULL,
	[product_id] [int] NOT NULL,
	[amount] [int] NOT NULL,
	[price] [decimal](8, 2) NULL,
	[cost]  AS ([price]*[amount])
) ON [PRIMARY]
GO

# [dbo].[OrdersOrderDetailsCustomersView]

In [0]:
/****** Object:  View [dbo].[OrdersOrderDetailsCustomersView]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create view [dbo].[OrdersOrderDetailsCustomersView] as
select orders.order_id,
	   customer_name,
	   order_date,
	   orders.order_status,
       products.product_id,
	   product_name,
       amount,
	   price,
	   cost
		from orders 
			join order_details on orders.order_id=order_details.order_id 
			join products on order_details.product_id=products.product_id
			join customers on orders.customer_id=customers.customer_id
GO

# [dbo].[discounts]

In [0]:
/****** Object:  Table [dbo].[discounts]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[discounts](
	[product_id] [int] NOT NULL,
	[discount] [decimal](3, 2) NOT NULL
) ON [PRIMARY]
GO

# [dbo].[users]

In [0]:
/****** Object:  Table [dbo].[users]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[user_id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](30) NOT NULL,
	[user_password] [varbinary](256) NOT NULL,
	[user_role] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[workers]

In [0]:
/****** Object:  Table [dbo].[workers]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[workers](
	[user_id] [int] NOT NULL,
	[worker_id] [int] IDENTITY(1,1) NOT NULL,
	[email] [varchar](30) NOT NULL,
	[first_name] [varchar](30) NOT NULL,
	[second_name] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[worker_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [DF__orders__order_st__3B75D760]

In [0]:
ALTER TABLE [dbo].[orders] ADD  DEFAULT ('pending') FOR [order_status]
GO

# [FK__customers__user___33D4B598]

In [0]:
ALTER TABLE [dbo].[customers]  WITH CHECK ADD FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([user_id])
GO

# [FK__discounts__produ__4316F928]

In [0]:
ALTER TABLE [dbo].[discounts]  WITH CHECK ADD FOREIGN KEY([product_id])
REFERENCES [dbo].[products] ([product_id])
GO

# [FK__order_det__order__46E78A0C]

In [0]:
ALTER TABLE [dbo].[order_details]  WITH CHECK ADD FOREIGN KEY([order_id])
REFERENCES [dbo].[orders] ([order_id])
GO

# [FK__order_det__produ__47DBAE45]

In [0]:
ALTER TABLE [dbo].[order_details]  WITH CHECK ADD FOREIGN KEY([product_id])
REFERENCES [dbo].[products] ([product_id])
GO

# [FK__orders__customer__3A81B327]

In [0]:
ALTER TABLE [dbo].[orders]  WITH CHECK ADD FOREIGN KEY([customer_id])
REFERENCES [dbo].[customers] ([customer_id])
GO

# [FK__stock__product_i__4CA06362]

In [0]:
ALTER TABLE [dbo].[stock]  WITH CHECK ADD FOREIGN KEY([product_id])
REFERENCES [dbo].[products] ([product_id])
GO

# [FK__workers__user_id__2C3393D0]

In [0]:
ALTER TABLE [dbo].[workers]  WITH CHECK ADD FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([user_id])
ON DELETE CASCADE
GO

# [CK__customers__addre__37A5467C]

In [0]:
ALTER TABLE [dbo].[customers]  WITH CHECK ADD CHECK  (([address]<>''))
GO

# [CK__customers__custo__35BCFE0A]

In [0]:
ALTER TABLE [dbo].[customers]  WITH CHECK ADD CHECK  (([customer_name]<>''))
GO

# [CK_CUSTOMER_EMAIL]

In [0]:
ALTER TABLE [dbo].[customers]  WITH CHECK ADD  CONSTRAINT [CK_CUSTOMER_EMAIL] CHECK  (([dbo].[isValidEmail]([email])=(1)))
GO
ALTER TABLE [dbo].[customers] CHECK CONSTRAINT [CK_CUSTOMER_EMAIL]
GO

# [CK_CUSTOMER_PHONE_NUMBER]

In [0]:
ALTER TABLE [dbo].[customers]  WITH CHECK ADD  CONSTRAINT [CK_CUSTOMER_PHONE_NUMBER] CHECK  (([dbo].[isValidPhoneNumber]([phone_number])=(1)))
GO
ALTER TABLE [dbo].[customers] CHECK CONSTRAINT [CK_CUSTOMER_PHONE_NUMBER]
GO

# [CK__products__produc__403A8C7D]

In [0]:
ALTER TABLE [dbo].[products]  WITH CHECK ADD CHECK  (([product_name]<>''))
GO

# [CK__users__user_pass__286302EC]

In [0]:
ALTER TABLE [dbo].[users]  WITH CHECK ADD CHECK  (([user_password]<>''))
GO

# [CK__users__username__276EDEB3]

In [0]:
ALTER TABLE [dbo].[users]  WITH CHECK ADD CHECK  (([username]<>''))
GO

# [CK__workers__first_n__2E1BDC42]

In [0]:
ALTER TABLE [dbo].[workers]  WITH CHECK ADD CHECK  (([first_name]<>''))
GO

# [CK__workers__second___2F10007B]

In [0]:
ALTER TABLE [dbo].[workers]  WITH CHECK ADD CHECK  (([second_name]<>''))
GO

# [CK_WORKER_EMAIL]

In [0]:
ALTER TABLE [dbo].[workers]  WITH CHECK ADD  CONSTRAINT [CK_WORKER_EMAIL] CHECK  (([dbo].[isValidEmail]([email])=(1)))
GO
ALTER TABLE [dbo].[workers] CHECK CONSTRAINT [CK_WORKER_EMAIL]
GO

# [dbo].[DeleteWorker]

In [0]:
/****** Object:  StoredProcedure [dbo].[DeleteWorker]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[DeleteWorker]
	@worker_id int
as
	DELETE from users
		where user_id=@worker_id
GO

# [dbo].[InsertCustomer]

In [0]:
/****** Object:  StoredProcedure [dbo].[InsertCustomer]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[InsertCustomer]
	@customer_name varchar(30),
	@email varchar(30),
	@phone_number varchar(30),
	@address varchar(30),
	@user_password varchar(30)
as
BEGIN
	BEGIN TRANSACTION
		INSERT INTO users(username,
				user_password,
				user_role) 
			VALUES (left(@email, charindex('@', @email) - 1),
					HASHBYTES('SHA2_256', @user_password), 
					'customer')
		IF (@@error <> 0)
        	ROLLBACK
		INSERT INTO customers(user_id, 
				email,
				customer_name, 
				phone_number,
				address)
			VALUES ((select user_id from users
					where username=left(@email,  charindex('@', @email) - 1)),
				@email,
				@customer_name,
				@phone_number,
				@address
			)
		IF (@@error <> 0)
        	ROLLBACK
	COMMIT
END
GO

# [dbo].[InsertOrder]

In [0]:
/****** Object:  StoredProcedure [dbo].[InsertOrder]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[InsertOrder]
	@customer_id INT,
	@order_date DATETIME
as
	INSERT INTO orders(customer_id, order_date) 
		VALUES (@customer_id, @order_date)
GO

# [dbo].[InsertOrder_details]

In [0]:
/****** Object:  StoredProcedure [dbo].[InsertOrder_details]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[InsertOrder_details]
	@order_id INT,
	@product_id INT,
	@amount INT
as
	INSERT INTO order_details(order_id, product_id, amount) 
		VALUES (@order_id, @product_id, @amount)
GO

# [dbo].[InsertProduct]

In [0]:
/****** Object:  StoredProcedure [dbo].[InsertProduct]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
---
create procedure [dbo].[InsertProduct]
	@product_name varchar(30),
	@product_type varchar(30),
	@upc_code varchar(12),
	@prime_price decimal(8, 2)
as
INSERT INTO products(product_name, product_type, upc_code, prime_price) 
	VALUES (@product_name, @product_type, @upc_code, @prime_price)
GO

# [dbo].[InsertWorker]

In [0]:
/****** Object:  StoredProcedure [dbo].[InsertWorker]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

---
create procedure [dbo].[InsertWorker]
	@email varchar(30),
	@first_name varchar(30),
	@second_name varchar(30),
	@user_password varchar(30)
as
BEGIN
	INSERT INTO users(username, user_password, user_role) 
		VALUES (left(@email, charindex('@', @email) - 1), HASHBYTES('SHA2_256', @user_password), 'worker');
	INSERT INTO workers(user_id, email, first_name, second_name)
		VALUES (
			(select user_id from users
				where username=left(@email,  charindex('@', @email) - 1)),
			@email,
			@first_name,
			@second_name
		)
END
GO

# [dbo].[ShowAllIncome]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowAllIncome]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
---
create procedure [dbo].[ShowAllIncome]
as
select sum(total_cost - total_prime_cost) as income 
	from Orders
where order_status='completed'
GO

# [dbo].[ShowAllOrders]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowAllOrders]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--
create procedure [dbo].[ShowAllOrders]
as
select order_id, 
	   customer_name, 
	   order_date,
	   order_status,
	   total_prime_cost,
	   total_cost 
from Orders 
	join customers 
		on orders.customer_id=customers.customer_id
GO

# [dbo].[ShowCustomers]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowCustomers]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
---
create procedure [dbo].[ShowCustomers]
as
select customer_name,
	email,
	phone_number,
	address
from customers
GO

# [dbo].[ShowIncomeByCustomer_id]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowIncomeByCustomer_id]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
---
create procedure [dbo].[ShowIncomeByCustomer_id]
	@customer_id int
as
select sum(total_cost - total_prime_cost) as income 
	from Orders
where order_status='completed' and customer_id=@customer_id
GO

# [dbo].[ShowLackProducts]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowLackProducts]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--
create procedure [dbo].[ShowLackProducts]
as
select product_name, 
	   abs(amount_on_stock - ordered) as lack_on_stock 
from (select product_name, 
			 sum(OrdersOrderDetailsCustomersView.amount) as ordered, 
			 stock.amount as amount_on_stock
	  from OrdersOrderDetailsCustomersView 
	  	  join stock 
		  	  on OrdersOrderDetailsCustomersView.product_id=stock.product_id
	  where order_status != 'completed'
	  group by product_name, stock.amount) 
as a
where (amount_on_stock - ordered) < 0
GO

# [dbo].[ShowLackProductsByCustomer_name]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowLackProductsByCustomer_name]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
---
create procedure [dbo].[ShowLackProductsByCustomer_name]
	@customer_name varchar(30)
as
select product_name, 
	abs(amount_on_stock - ordered) as lack_on_stock 
from
	(select product_name, 
		sum(OrdersOrderDetailsCustomersView.amount) as ordered, 
		stock.amount as amount_on_stock
	from OrdersOrderDetailsCustomersView join stock on OrdersOrderDetailsCustomersView.product_id=stock.product_id
	where order_status != 'completed' and customer_name = @customer_name
	group by product_name, stock.amount) 
as a
where (amount_on_stock - ordered) < 0
GO

# [dbo].[ShowLackProductsByOrder_id]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowLackProductsByOrder_id]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
---
create procedure [dbo].[ShowLackProductsByOrder_id]
	@order_id int
as
select product_name, 
	abs(amount_on_stock - ordered) as lack_on_stock 
from
	(select product_name, 
		sum(OrdersOrderDetailsCustomersView.amount) as ordered, 
		stock.amount as amount_on_stock
	from OrdersOrderDetailsCustomersView 
		join stock on OrdersOrderDetailsCustomersView.product_id=stock.product_id
	where order_status != 'completed' and order_id = @order_id
group by product_name, stock.amount) 
as a
where (amount_on_stock - ordered) < 0
GO

# [dbo].[ShowOrderDetails]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowOrderDetails]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
---
create procedure [dbo].[ShowOrderDetails]
@order_id int
as
select product_name, amount, price, cost
	from OrdersOrderDetailsCustomersView
	where order_id = @order_id
GO

# [dbo].[ShowOrdersByCustomer_id]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowOrdersByCustomer_id]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--
create procedure [dbo].[ShowOrdersByCustomer_id]
	@customer_id int
as
select order_id,
	order_date,
	order_status, 
	total_cost 
from Orders
where customer_id = @customer_id
GO

# [dbo].[ShowOrdersByCustomer_idAndOrder_status]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowOrdersByCustomer_idAndOrder_status]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--
create procedure [dbo].[ShowOrdersByCustomer_idAndOrder_status]
	@customer_id int,
	@order_status varchar(30)
as
select order_id,
	order_date,
	order_status, 
	total_cost
from Orders
where customer_id = @customer_id and order_status = @order_status
GO

# [dbo].[ShowProductsBase]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowProductsBase]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--PROCEDURES
create procedure [dbo].[ShowProductsBase] 
as
select * from ProductsStockView
GO

# [dbo].[ShowProductsCatalog]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowProductsCatalog]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--
create procedure [dbo].[ShowProductsCatalog] 
as
select product_name,
	   product_type,
	   retail_price, 
	   discount_price 
from ProductsStockView
GO

# [dbo].[ShowWorkers]

In [0]:
/****** Object:  StoredProcedure [dbo].[ShowWorkers]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
---
create procedure [dbo].[ShowWorkers]
as
select email, 
	username, 
	first_name, 
	second_name 
from workers 
	join users on workers.user_id=users.user_id
GO

# [dbo].[UpdateAmountOnStock]

In [0]:
/****** Object:  StoredProcedure [dbo].[UpdateAmountOnStock]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[UpdateAmountOnStock]
	@product_id int,
	@amount int
as
	UPDATE stock
		set amount = @amount
	where product_id=@product_id
GO

# [dbo].[UpdateCustomer]

In [0]:
/****** Object:  StoredProcedure [dbo].[UpdateCustomer]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[UpdateCustomer]
	@customer_id int,
	@phone_number varchar(30),
	@address varchar(30)
as
	UPDATE customers
		set phone_number = @phone_number,
			address = @address
	where customer_id=@customer_id
GO

# [dbo].[UpdateDiscount]

In [0]:
/****** Object:  StoredProcedure [dbo].[UpdateDiscount]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[UpdateDiscount]
	@product_id int,
	@discount decimal(3, 2)
as
	UPDATE discounts
		set discount = @discount
	where product_id=@product_id
GO

# [dbo].[UpdateOrderStatus]

In [0]:
/****** Object:  StoredProcedure [dbo].[UpdateOrderStatus]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[UpdateOrderStatus]
	@order_id int,
	@order_status varchar(30)
as
	UPDATE orders
		set order_status = @order_status
	where order_id=@order_id
GO

# [dbo].[UpdateProduct]

In [0]:
/****** Object:  StoredProcedure [dbo].[UpdateProduct]    Script Date: 27.11.2022 23:42:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create procedure [dbo].[UpdateProduct]
	@product_id int,
	@product_name varchar(30),
	@product_type varchar(30),
	@upc_code varchar(30),
	@prime_price varchar(30)
as
	UPDATE products
		set product_name = @product_name,
			product_type = @product_type,
			upc_code = @upc_code,
			prime_price = @prime_price
	where product_id=@product_id
GO

# [brewery]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [brewery] SET  READ_WRITE 
GO